CREATE TABLE methode (
id INT PRIMARY KEY NOT NULL,
nomMethode VARCHAR(20) NOT NULL,
proba INT NOT NULL);

CREATE TABLE pokemon (
id INT PRIMARY KEY NOT NULL,
nomPoke VARCHAR(30) NOT NULL,
pathToSprite VARCHAR(45) NOT NULL,
pathToAlola VARCHAR(45),
pathToGalar VARCHAR(45),
pathToHisui VARCHAR(45));

CREATE TABLE ShasseCourante (
id INT PRIMARY KEY NOT NULL,
username VARCHAR(20) NOT NULL,
nomPoke VARCHAR(30) NOT NULL,
methode VARCHAR(20) NOT NULL,
nombre INT NOT NULL,
generation VARCHAR(20)NOT NULL);

CREATE TABLE captures (
id INT PRIMARY KEY NOT NULL,
username VARCHAR(20) NOT NULL,
numero INT NOT NULL,
nomPoke VARCHAR(30) NOT NULL,
methode VARCHAR(20) NOT NULL,
nombre INT NOT NULL,
date DATE NOT NULL,
jeu VARCHAR(20) NOT NULL,
generation VARCHAR(20) NOT NULL);
